version: '3.3'
services:
  https-portal:
    image: steveltn/https-portal:1.6.1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    links:
      - nginx
    environment:
      STAGE: 'production'
      DOMAINS: 'ucpr.dev -> http://nginx/'

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    restart: always
